"""Sampling moire analysis for displacement and strain measurement."""

__version__ = "0.1.1"

from .core import (
    AnalysisResult,
    GridAnalysisResult,
    StrainResult,
    analyze,
    analyze_grid,
    displacement,
    phase_shifted_stack,
    phase_shifted_sampling_moire,
    recommended_strain_smoothing_window,
    separate_grid_components,
    smooth_axis,
    strain_field,
    unwrap_phase,
    wrapped_phase,
)
from .geometry import (
    PerspectiveCalibration,
    apply_homography,
    crop_roi,
    homography_from_points,
    pixel_spacing_from_world_points,
    rectangle_points,
    rectify_image,
    rectify_image_pair,
    resample_oblique_grid,
    sample_bilinear,
    warp_perspective,
)
from .io import load_grayscale_image, save_analysis_npz, save_grayscale_image
from .masking import apply_valid_mask, crop_to_mask, inner_valid_mask, mask_bounds, robust_limits
from .plotting import save_grid_analysis_figure, save_grid_truth_comparison_figure
from .roi import GratingROI, crop_grating_roi, detect_grating_roi, grating_energy
from .synthetic import SyntheticExperiment, make_microstrain_experiment, save_experiment_npz
from .synthetic import (
    SyntheticSquareGridExperiment,
    SyntheticStrainExperiment,
    make_microstrain_square_grid,
    make_strain_distribution_experiment,
    save_square_grid_experiment_npz,
    save_strain_experiment_npz,
)

__all__ = [
    "__version__",
    "AnalysisResult",
    "GratingROI",
    "GridAnalysisResult",
    "PerspectiveCalibration",
    "StrainResult",
    "SyntheticExperiment",
    "SyntheticSquareGridExperiment",
    "SyntheticStrainExperiment",
    "analyze",
    "analyze_grid",
    "apply_homography",
    "crop_roi",
    "crop_grating_roi",
    "detect_grating_roi",
    "displacement",
    "homography_from_points",
    "grating_energy",
    "make_microstrain_experiment",
    "make_microstrain_square_grid",
    "make_strain_distribution_experiment",
    "phase_shifted_stack",
    "phase_shifted_sampling_moire",
    "pixel_spacing_from_world_points",
    "rectangle_points",
    "rectify_image",
    "rectify_image_pair",
    "recommended_strain_smoothing_window",
    "resample_oblique_grid",
    "save_analysis_npz",
    "save_experiment_npz",
    "save_grid_analysis_figure",
    "save_grid_truth_comparison_figure",
    "save_grayscale_image",
    "save_square_grid_experiment_npz",
    "save_strain_experiment_npz",
    "separate_grid_components",
    "sample_bilinear",
    "smooth_axis",
    "apply_valid_mask",
    "crop_to_mask",
    "inner_valid_mask",
    "load_grayscale_image",
    "mask_bounds",
    "robust_limits",
    "strain_field",
    "unwrap_phase",
    "warp_perspective",
    "wrapped_phase",
]
